let TempStore = {
    cars: [
        // {
        //     "id": 1,
        //     "name": "LADA Granta",
        //     "year": 2015,
        //     "ownersCount": 2,
        //     "mileage": 145000,
        //     "isBroked": false,
        //     "color": 13,  // фиолетовый
        //     "isShowroom": false,
        //     "transmission": 2,  // механика
        //     "drive": 1,  // передний
        //     "bodyType": 1, // седан
        //     "volume": 1.5,
        //     enginePower: 125,
        //     "isRight": false,
        //     "price": '615000',
        //     "settlement": 'Москва',
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6308412/fea022e17d3758cebe9bfca8c6706536/320x240",
        //     ownerName: 'Владик',
        //     adFrom: 'Авито',
        //     reference: 'https://auto.ru/cars/used/sale/vaz/granta/1114894832-03045815/?from=searchline',
        //     postDate: '2022-03-05T13:51',
        //     "isFavourite": true
        // },
        {
            "id": 110312469,
            "name": "Ford Mondeo",
            "year": 1997,
            "price": 190000,
            "mileage": 320000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Рыбхоз",
            "ownersCount": 3,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.8,
            "color": 13,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6308412/fea022e17d3758cebe9bfca8c6706536/320x240",
            "phoneCount": 5,
            "previousPrice": null,
            "markId": 20,
            "modelId": 28,
            "generationId": 3946,
            "modificationId": null,
            "regionId": 79,
            "diff": 80,
            "diffLiteral": "т.р",
            "avgPriceType": "act+sold3",
            "localTime": "2022-03-09T10:15:49.487",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 8,
            "publishDate": "2022-03-09T10:13:28",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": false,
            "clicked": false,
            "clickedByOther": false,
            "called": true,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 3,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 108887989,
            "name": "LADA (ВАЗ) Priora",
            "year": 2007,
            "price": 140000,
            "mileage": 160200,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Орехово-Зуево",
            "ownersCount": 4,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.6,
            "color": 6,
            "power": null,
            "isRight": false,
            "isFakeNumber": false,
            "imageUrl": "https://96.img.avito.st/208x156/12970283496.jpg",
            "phoneCount": 1,
            "previousPrice": 150000,
            "markId": 65,
            "modelId": 1,
            "generationId": 3804,
            "modificationId": null,
            "regionId": 79,
            "diff": -10,
            "diffLiteral": "т.р",
            "avgPriceType": "actpub3",
            "localTime": "2022-03-09T10:12:04.977",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 18,
            "publishDate": "2022-02-02T21:04:29",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": true,
            "clicked": false,
            "clickedByOther": true,
            "called": true,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 2,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110259632,
            "name": "Renault Logan",
            "year": 2009,
            "price": 148000,
            "mileage": 170000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Москва",
            "ownersCount": 2,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.4,
            "color": 2,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://80.img.avito.st/208x156/13020015580.jpg",
            "phoneCount": 1,
            "previousPrice": 150000,
            "markId": 54,
            "modelId": 13,
            "generationId": 3852,
            "modificationId": null,
            "regionId": 79,
            "diff": -102,
            "diffLiteral": "т.р",
            "avgPriceType": "near+act+sold3",
            "localTime": "2022-03-09T10:12:02.503",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 5,
            "publishDate": "2022-03-07T10:35:53",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": 110250493,
            "hasDouble": true,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 2,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110312346,
            "name": "LADA (ВАЗ) 2115",
            "year": 2004,
            "price": 105000,
            "mileage": 150000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Москва",
            "ownersCount": 3,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.5,
            "color": 4,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6484303/52f413545c279fecaf0a42a169a821a6/320x240",
            "phoneCount": 5,
            "previousPrice": null,
            "markId": 65,
            "modelId": 220,
            "generationId": 4758,
            "modificationId": null,
            "regionId": 79,
            "diff": 20,
            "diffLiteral": "т.р",
            "avgPriceType": "actpub3",
            "localTime": "2022-03-09T10:11:34.153",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 8,
            "publishDate": "2022-03-09T10:08:50",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": true,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 3,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110312321,
            "name": "Nissan Maxima",
            "year": 1998,
            "price": 170000,
            "mileage": 261207,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Коломна",
            "ownersCount": 3,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 2,
            "color": 4,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/5982845/e19ff489f08f682e91d268577825dbbc/320x240",
            "phoneCount": 8,
            "previousPrice": null,
            "markId": 50,
            "modelId": 208,
            "generationId": 4708,
            "modificationId": null,
            "regionId": 79,
            "diff": 32,
            "diffLiteral": "т.р",
            "avgPriceType": "act+sold3",
            "localTime": "2022-03-09T10:09:32.727",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 11,
            "publishDate": "2022-03-09T10:06:56",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": false,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 3,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110312320,
            "name": "Daewoo Nexia",
            "year": 2001,
            "price": 95555,
            "mileage": 111111,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Москва",
            "ownersCount": 3,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.5,
            "color": 4,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6022602/aa9b3aea4a5005a9080501bbe3717619/320x240",
            "phoneCount": 2,
            "previousPrice": null,
            "markId": 15,
            "modelId": 18,
            "generationId": 3899,
            "modificationId": null,
            "regionId": 79,
            "diff": 3,
            "diffLiteral": "т.р",
            "avgPriceType": "actpub3",
            "localTime": "2022-03-09T10:09:28.997",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 1,
            "publishDate": "2022-03-09T10:05:00",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": 110299063,
            "hasDouble": true,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 3,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110312297,
            "name": "Daewoo Nexia",
            "year": 2003,
            "price": 89000,
            "mileage": 234000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Ликино-Дулево",
            "ownersCount": 2,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.5,
            "color": 7,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://76.img.avito.st/image/1/1.hQSHeLa_Ke2p2fnugVq5Q1HbL-c5eyhXM9sr6TNDKT0w2w.1CGCONQi3RSKCzjLbc8zCnrO_IQO8Rh3fen8OjklM1E",
            "phoneCount": 2,
            "previousPrice": null,
            "markId": 15,
            "modelId": 18,
            "generationId": 3899,
            "modificationId": null,
            "regionId": 79,
            "diff": -16,
            "diffLiteral": "т.р",
            "avgPriceType": "actpub3",
            "localTime": "2022-03-09T10:08:33.963",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 20,
            "publishDate": "2022-03-09T10:07:37",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": false,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 2,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110312271,
            "name": "LADA (ВАЗ) Kalina",
            "year": 2009,
            "price": 245000,
            "mileage": 124000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Балашиха",
            "ownersCount": 2,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.6,
            "color": 6,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6303976/b45e6335d108a46988fff6cbd968f31e/320x240",
            "phoneCount": 5,
            "previousPrice": null,
            "markId": 65,
            "modelId": 2,
            "generationId": 3806,
            "modificationId": null,
            "regionId": 79,
            "diff": 106,
            "diffLiteral": "т.р",
            "avgPriceType": "act+sold3",
            "localTime": "2022-03-09T10:06:24.64",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 1,
            "publishDate": "2022-03-09T10:03:52",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": 110298889,
            "hasDouble": true,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 3,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110216005,
            "name": "LADA (ВАЗ) 2115",
            "year": 2003,
            "price": 90000,
            "mileage": 180000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Развилка",
            "ownersCount": 3,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.5,
            "color": 2,
            "power": null,
            "isRight": false,
            "isFakeNumber": true,
            "imageUrl": "https://18.img.avito.st/208x156/13025840018.jpg",
            "phoneCount": 3,
            "previousPrice": 95000,
            "markId": 65,
            "modelId": 220,
            "generationId": 4758,
            "modificationId": null,
            "regionId": 79,
            "diff": -5,
            "diffLiteral": "т.р",
            "avgPriceType": "actpub3",
            "localTime": "2022-03-09T10:02:45.443",
            "isPhoneRegion": null,
            "is404": false,
            "imagesCount": 9,
            "publishDate": "2022-03-05T18:52:04",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": false,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 2,
            "vin": null,
            "tags": [
                5
            ],
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110145421,
            "name": "Volvo 460",
            "year": 1991,
            "price": 95000,
            "mileage": 215000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Щербинка",
            "ownersCount": 4,
            "isBroked": false,
            "isShowroom": false,
            "drive": 1,
            "engine": 1,
            "volume": 1.7,
            "color": 6,
            "power": null,
            "isRight": false,
            "isFakeNumber": false,
            "imageUrl": "https://63.img.avito.st/208x156/12990172663.jpg",
            "phoneCount": 4,
            "previousPrice": 96000,
            "markId": null,
            "modelId": null,
            "generationId": null,
            "modificationId": null,
            "regionId": 79,
            "diff": null,
            "diffLiteral": null,
            "avgPriceType": null,
            "localTime": "2022-03-09T10:01:28.33",
            "isPhoneRegion": true,
            "is404": false,
            "imagesCount": 11,
            "publishDate": "2022-03-03T21:17:59",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": false,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 2,
            "vin": null,
            "tags": null,
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        {
            "id": 110155566,
            "name": "Nissan Primera",
            "year": 1997,
            "price": 99000,
            "mileage": 230000,
            "bodyType": 1,
            "transmission": 2,
            "settlement": "Москва",
            "ownersCount": 4,
            "isBroked": false,
            "isShowroom": true,
            "drive": 1,
            "engine": 1,
            "volume": 1.6,
            "color": 6,
            "power": null,
            "isRight": false,
            "isFakeNumber": false,
            "imageUrl": "https://82.img.avito.st/208x156/12993639682.jpg",
            "phoneCount": 24,
            "previousPrice": 105000,
            "markId": 50,
            "modelId": 73,
            "generationId": 4202,
            "modificationId": null,
            "regionId": 79,
            "diff": 11,
            "diffLiteral": "т.р",
            "avgPriceType": "act+sold3",
            "localTime": "2022-03-09T10:01:27.397",
            "isPhoneRegion": true,
            "is404": false,
            "imagesCount": 8,
            "publishDate": "2022-03-04T10:04:27",
            "saleDate": null,
            "hasRegHistory": false,
            "mainId": null,
            "hasDouble": false,
            "clicked": false,
            "clickedByOther": false,
            "called": false,
            "favoriteId": null,
            "favorite": null,
            "rowColor": null,
            "shopId": null,
            "externSource": 2,
            "vin": null,
            "tags": [
                5
            ],
            "rating": null,
            "isRestrict": null,
            "isFavoriteShop": null,
            "isFavoriteDouble": null,
            "favoriteShopOwnerId": null,
            "favoriteDoublesAmount": null,
            "auctionId": null,
            "placeholder": null,
            "saleDays": null,
            "inStock": null,
            "isCurrent": null,
            "isExclude": false,
            "eventType": null,
            "advertUrl": null,
            "advertUserCallId": null,
            "phone": null,
            "sellerName": null,
            "auctionLotShort": null
        },
        // {
        //     "id": 110034222,
        //     "name": "Daewoo Nexia",
        //     "year": 2008,
        //     "price": 87000,
        //     "mileage": 248000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Котельники",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.5,
        //     "color": 3,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": false,
        //     "imageUrl": "https://28.img.avito.st/208x156/12976307128.jpg",
        //     "phoneCount": 0,
        //     "previousPrice": 95000,
        //     "markId": 15,
        //     "modelId": 18,
        //     "generationId": 3898,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -35,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T10:01:00.763",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 4,
        //     "publishDate": "2022-02-28T21:20:03",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": 109994721,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": [
        //         5
        //     ],
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110312088,
        //     "name": "LADA (ВАЗ) 21099",
        //     "year": 2001,
        //     "price": 110000,
        //     "mileage": 133000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.5,
        //     "color": 5,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6201759/4a5867d3bad3fe1d679b8002068c48f3/320x240",
        //     "phoneCount": 8,
        //     "previousPrice": null,
        //     "markId": 65,
        //     "modelId": 477,
        //     "generationId": 5434,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": 25,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:59:19.227",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 11,
        //     "publishDate": "2022-03-09T09:57:07",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110312019,
        //     "name": "Daewoo Nexia",
        //     "year": 2007,
        //     "price": 120000,
        //     "mileage": 152000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.5,
        //     "color": 2,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": null,
        //     "imageUrl": "https://cdn0.youla.io/files/images/orig/62/28/6228477684e80e4cd21f354e-1.jpg",
        //     "phoneCount": 0,
        //     "previousPrice": null,
        //     "markId": 15,
        //     "modelId": 18,
        //     "generationId": 3899,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -9,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:55:12.657",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 6,
        //     "publishDate": "2022-03-09T09:55:12.637",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 12,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110311848,
        //     "name": "Peugeot 206",
        //     "year": 2008,
        //     "price": 241000,
        //     "mileage": 141000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Серпухов",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.4,
        //     "color": 1,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://48.img.avito.st/image/1/1.kYNAjba_PWpuLO1pbp-Q4pcuO2D-jjzQ9C4_bvS2Pbr3Lg.56GuaarV05sUhGMYNFqJaw6H8f012bPCy34s20Lfv1c",
        //     "phoneCount": 1,
        //     "previousPrice": null,
        //     "markId": 52,
        //     "modelId": 81,
        //     "generationId": 4221,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -35,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:49:20.493",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 8,
        //     "publishDate": "2022-03-09T09:44:02",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110193609,
        //     "name": "LADA (ВАЗ) Priora",
        //     "year": 2008,
        //     "price": 225000,
        //     "mileage": 152000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Серпухов",
        //     "ownersCount": 4,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.6,
        //     "color": 4,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": null,
        //     "imageUrl": "https://cdn0.youla.io/files/images/orig/62/23/62230a712ea3ac51b92e8600-1.jpg",
        //     "phoneCount": 0,
        //     "previousPrice": 235000,
        //     "markId": 65,
        //     "modelId": 1,
        //     "generationId": 3804,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": 50,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:44:51.99",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 2,
        //     "publishDate": "2022-03-05T10:03:00.12",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": 109889926,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 12,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 109831193,
        //     "name": "Renault Logan",
        //     "year": 2006,
        //     "price": 165000,
        //     "mileage": 280000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Томилино",
        //     "ownersCount": 4,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.4,
        //     "color": 5,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://03.img.avito.st/208x156/13025085803.jpg",
        //     "phoneCount": 1,
        //     "previousPrice": 170000,
        //     "markId": 54,
        //     "modelId": 13,
        //     "generationId": 3853,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -47,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:41:13.543",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 6,
        //     "publishDate": "2022-02-23T19:41:37",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110311373,
        //     "name": "LADA (ВАЗ) 2107",
        //     "year": 2007,
        //     "price": 130000,
        //     "mileage": 49700,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 1,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 2,
        //     "engine": 1,
        //     "volume": 1.6,
        //     "color": 5,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://45.img.avito.st/image/1/1.uJChiba_FHmPKMR63fu68XYqEnMfihXDFSoWfRWyFKkWKg.a_ZdQYnRJvdpp7fNeOsthh-9ycdJa19Is_RLhksROmo",
        //     "phoneCount": 1,
        //     "previousPrice": null,
        //     "markId": 65,
        //     "modelId": 249,
        //     "generationId": 4860,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": 35,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:31:54.653",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 4,
        //     "publishDate": "2022-03-09T09:31:17",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110311282,
        //     "name": "Saab 9-5",
        //     "year": 2000,
        //     "price": 280000,
        //     "mileage": 350000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Егорьевск",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 2.3,
        //     "color": 5,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/4387583/8d982729c7876cffe1574a2eb8eb71d4/320x240",
        //     "phoneCount": 5,
        //     "previousPrice": null,
        //     "markId": 56,
        //     "modelId": 986,
        //     "generationId": 6641,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": 130,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "act+sold3",
        //     "localTime": "2022-03-09T09:30:25.24",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 11,
        //     "publishDate": "2021-06-24T11:53:01",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 109889926,
        //     "name": "LADA (ВАЗ) Priora",
        //     "year": 2008,
        //     "price": 225000,
        //     "mileage": 155000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Серпухов",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.6,
        //     "color": 4,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6012221/686e1d4e32611fdb5110ea7d6b4baf81/320x240",
        //     "phoneCount": 8,
        //     "previousPrice": 235000,
        //     "markId": 65,
        //     "modelId": 1,
        //     "generationId": 3804,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": 50,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:24:57.21",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 8,
        //     "publishDate": "2022-02-25T10:10:31",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110311049,
        //     "name": "LADA (ВАЗ) 2115",
        //     "year": 2009,
        //     "price": 115000,
        //     "mileage": 147000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Подольск",
        //     "ownersCount": 2,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.6,
        //     "color": 2,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://00.img.avito.st/image/1/1.vczUSLa_ESX66cEmog6xrQPrFy9qSxCfYOsTIWBzEfVj6w.2T4wPtT9FhO6kNt--8IjlDWl8CErTPA42dsLtgnSxT0",
        //     "phoneCount": 2,
        //     "previousPrice": null,
        //     "markId": 65,
        //     "modelId": 220,
        //     "generationId": 4758,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -10,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:18:23.91",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 13,
        //     "publishDate": "2022-03-09T09:18:09",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110311009,
        //     "name": "Hyundai Accent",
        //     "year": 2007,
        //     "price": 95000,
        //     "mileage": 150000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Сергиев Посад",
        //     "ownersCount": 2,
        //     "isBroked": true,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.5,
        //     "color": 2,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://38.img.avito.st/image/1/1.dzMMmra_29oiOwvZbr94Uts53dCymdpguDnZ3rih2wq7OQ.lofiLFGdOAIVh3Y1W09FiBiJkGbR_qczFiWTLZLIG0g",
        //     "phoneCount": 4,
        //     "previousPrice": null,
        //     "markId": 29,
        //     "modelId": 19,
        //     "generationId": 3904,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -195,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:16:40.417",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 7,
        //     "publishDate": "2022-03-09T09:15:51",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110269412,
        //     "name": "LADA (ВАЗ) Priora",
        //     "year": 2007,
        //     "price": 105000,
        //     "mileage": 250000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.6,
        //     "color": 4,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/5993563/d703f0fb557574586621432b14525fda/320x240",
        //     "phoneCount": 7,
        //     "previousPrice": 115000,
        //     "markId": 65,
        //     "modelId": 1,
        //     "generationId": 3804,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -45,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:15:35.153",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 11,
        //     "publishDate": "2022-03-07T15:22:37",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 109994721,
        //     "name": "Daewoo Nexia",
        //     "year": 2008,
        //     "price": 87000,
        //     "mileage": 265000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Троицк",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.5,
        //     "color": 3,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/4612068/b73def5caf573ee3c451fd218695e033/320x240",
        //     "phoneCount": 4,
        //     "previousPrice": 96000,
        //     "markId": 15,
        //     "modelId": 18,
        //     "generationId": 3898,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -35,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:14:00.59",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 5,
        //     "publishDate": "2022-02-27T22:51:35",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110310860,
        //     "name": "LADA (ВАЗ) 2115",
        //     "year": 2007,
        //     "price": 150000,
        //     "mileage": 93000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 3,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.6,
        //     "color": 14,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6196574/ea305be5766e9acca8ce8714930288d8/320x240",
        //     "phoneCount": 9,
        //     "previousPrice": null,
        //     "markId": 65,
        //     "modelId": 220,
        //     "generationId": 4758,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": 51,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:09:37.353",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 10,
        //     "publishDate": "2022-03-09T09:07:38",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110193663,
        //     "name": "Daewoo Nexia",
        //     "year": 2007,
        //     "price": 139800,
        //     "mileage": 123500,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 2,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.5,
        //     "color": 9,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": false,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6483455/19c09f4b7ed206ae2d48047d307f8486/320x240",
        //     "phoneCount": 2,
        //     "previousPrice": 145000,
        //     "markId": 15,
        //     "modelId": 18,
        //     "generationId": 3899,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": 10,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T09:00:53.187",
        //     "isPhoneRegion": true,
        //     "is404": false,
        //     "imagesCount": 10,
        //     "publishDate": "2022-03-05T09:58:30",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 107497161,
        //     "name": "ГАЗ 3110 Волга",
        //     "year": 2001,
        //     "price": 100000,
        //     "mileage": 194000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 2,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 2,
        //     "engine": 1,
        //     "volume": 2.3,
        //     "color": 7,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://98.img.avito.st/208x156/12549189098.jpg",
        //     "phoneCount": 0,
        //     "previousPrice": 110000,
        //     "markId": 87,
        //     "modelId": 1855,
        //     "generationId": 7611,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -50,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "act",
        //     "localTime": "2022-03-09T08:59:54.583",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 22,
        //     "publishDate": "2021-12-27T19:16:14",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": true,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110310440,
        //     "name": "Ford Focus",
        //     "year": 2003,
        //     "price": 150000,
        //     "mileage": 283800,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 4,
        //     "isBroked": false,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.8,
        //     "color": 1,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://66.img.avito.st/image/1/1.A2DTHra_r4n9v3-K2X49AQS9qYNtHa4zZ72tjWclr1lkvQ.VchYOj3VvYuXLfz9_kjlfyui5aG7qDZQ8l4-PHaESGw",
        //     "phoneCount": 2,
        //     "previousPrice": null,
        //     "markId": 20,
        //     "modelId": 3,
        //     "generationId": 3812,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -80,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T08:45:34.607",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 9,
        //     "publishDate": "2022-03-09T08:44:40",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110310313,
        //     "name": "Iran Khodro Samand",
        //     "year": 2006,
        //     "price": 150000,
        //     "mileage": 162000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Подольск",
        //     "ownersCount": 3,
        //     "isBroked": true,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.8,
        //     "color": 1,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": true,
        //     "imageUrl": "https://avatars.mds.yandex.net/get-autoru-vos/6408148/c906f0b2fcadd7ff6123141e0cb000a2/320x240",
        //     "phoneCount": 12,
        //     "previousPrice": null,
        //     "markId": 76,
        //     "modelId": 478,
        //     "generationId": 5435,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -13,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "actpub3",
        //     "localTime": "2022-03-09T08:39:04.837",
        //     "isPhoneRegion": null,
        //     "is404": false,
        //     "imagesCount": 6,
        //     "publishDate": "2022-03-09T08:35:15",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 3,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // },
        // {
        //     "id": 110166964,
        //     "name": "Ford Focus",
        //     "year": 2003,
        //     "price": 169000,
        //     "mileage": 180000,
        //     "bodyType": 1,
        //     "transmission": 2,
        //     "settlement": "Москва",
        //     "ownersCount": 2,
        //     "isBroked": true,
        //     "isShowroom": false,
        //     "drive": 1,
        //     "engine": 1,
        //     "volume": 1.6,
        //     "color": 1,
        //     "power": null,
        //     "isRight": false,
        //     "isFakeNumber": false,
        //     "imageUrl": "https://75.img.avito.st/208x156/12995630475.jpg",
        //     "phoneCount": 1,
        //     "previousPrice": 179000,
        //     "markId": 20,
        //     "modelId": 3,
        //     "generationId": 3812,
        //     "modificationId": null,
        //     "regionId": 79,
        //     "diff": -13,
        //     "diffLiteral": "т.р",
        //     "avgPriceType": "act+sold3",
        //     "localTime": "2022-03-09T08:28:24.557",
        //     "isPhoneRegion": true,
        //     "is404": false,
        //     "imagesCount": 24,
        //     "publishDate": "2022-03-04T14:42:35",
        //     "saleDate": null,
        //     "hasRegHistory": false,
        //     "mainId": null,
        //     "hasDouble": false,
        //     "clicked": false,
        //     "clickedByOther": false,
        //     "called": false,
        //     "favoriteId": null,
        //     "favorite": null,
        //     "rowColor": null,
        //     "shopId": null,
        //     "externSource": 2,
        //     "vin": null,
        //     "tags": null,
        //     "rating": null,
        //     "isRestrict": null,
        //     "isFavoriteShop": null,
        //     "isFavoriteDouble": null,
        //     "favoriteShopOwnerId": null,
        //     "favoriteDoublesAmount": null,
        //     "auctionId": null,
        //     "placeholder": null,
        //     "saleDays": null,
        //     "inStock": null,
        //     "isCurrent": null,
        //     "isExclude": false,
        //     "eventType": null,
        //     "advertUrl": null,
        //     "advertUserCallId": null,
        //     "phone": null,
        //     "sellerName": null,
        //     "auctionLotShort": null
        // }
    ],
    news: [
        {
            id: 1,
            date: '2022-03-15T19:51',
            title: 'Уходят не все: японский бренд смазочных материалов видит перспективы в России',
            text: 'Компания уже начала заново отстраивать порушенные логистические цепочки.',
            whereFrom: 'ЗаРулём',
            reference: 'https://www.zr.ru/content/news/933770-ukhodyat-ne-vse-yaponskij-brend/'

        },
        {
            id: 2,
            date: '2022-03-15T21:03',
            title: 'Еврокомиссия запретила экспорт в Россию автомобилей дороже 50 000 евро',
            text: 'Еврокомиссия обнародовала меры в рамках четвёртого пакета санкций против России. В перечень вошёл, в частности, запрет на экспорт в нашу страну из Евросоюза автомобилей стоимостью более 50 000 евро (55 000 долларов). Аналогичный запрет, но без ограничения по сумме ввела Великобритания.',
            whereFrom: 'Авто.ру',
            reference: 'https://mag.auto.ru/article/evrokomissiya-zapretila-eksport-v-rossiyu-dorogih-mashin/'

        },
        {
            id: 3,
            date: '2022-03-09T11:40',
            title: 'Шин становится меньше: еще один крупный бренд покидает Россию',
            text: 'Приостанавливается завод в Ульяновске, а также прекращаются поставки продукции и инвестирование новых проектов, сообщили в Bridgestone.',
            whereFrom: 'ЗаРулём',
            reference: 'https://www.zr.ru/content/news/933775-shin-stanovitsya-menshe-eshche-odi/'

        },
        {
            id: 4,
            date: '2022-03-14T13:51',
            title: 'BMW и Audi нашли замену: 7 дорогих автомобилей, которые придут в Россию',
            text: 'Игроки высшего автомобильного эшелона приостановили деятельность в России. Какие модели могут их сменить, чтобы удовлетворить запросы обеспеченных покупателей',
            whereFrom: 'Autonews',
            reference: 'https://www.autonews.ru/news/622ee18e9a79474a3974808b'
        },
        {
            id: 5,
            date: '2022-03-14T14:44',
            title: '55 руб. за литр — это не предел: что будет с ценами на бензин',
            text: 'Более чем на 3,5 руб. выросли средние цены на литр 95-го бензина в Москве по сравнению прошлой весной. Но ФАС и ряд аналитиков уверяют: на фоне снижения оптовых цен топливо дешевеет.',
            whereFrom: 'Autonews',
            reference: 'https://www.autonews.ru/news/623050f69a7947d0da3d4f79'

        },
        {
            id: 6,
            date: '2022-03-02T11:40',
            title: 'Производитель мотоциклов Kawasaki представил робота-козла. На нём можно ездить верхом',
            text: 'Японский производитель мототехники Kawasaki на выставке роботов в Токио показал робота-козла. Назвали его Bex (Бекс), и внешне он действительно похож на животное, пишет Spectrum. Bex стал частью программы Kawasaki по созданию «надёжной гуманоидной платформы», которая реализуется с 2015 года.',
            whereFrom: 'Авто.ру',
            reference: 'https://mag.auto.ru/article/kawasaki-predstavila-robotakozla-na-kotorom-mozhno-ezdit-verhom/'

        }
    ],
}

export default TempStore;